name: Build and Check Format

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: v14.1.8
          cache: 'npm'
      - name: Install Packages
        run: npm install
      - name: Check Format
        run: npm run lint
      - name: Build
        run: npm run build  
